### ISSUE TITLE
vue-dropdowns VS nuxt

### ISSUE THREAD

**Issue by DoubleFacess** [mikerodham/vue-dropdowns#12]
HI,
try to install you lib as plugin in nuxt.js, but i cannot view your nice dropdown. Any idea to install it?

**Comment by mikerodham** [comment]
I've not used nuxt.js before, so I'm not entirely sure. The installation should be just as simple as in the readme if you're using .vue files. If it's not working, simply create a file in your project called `dropdown.vue` or similar, copy and paste the source code from [the file here](https://raw.githubusercontent.com/mikerodham/vue-dropdowns/master/Dropdown.vue) and use it as an import within your own project.

Hope this makes sense.
