### ISSUE TITLE
Unable to change the placeholder for multiple dropdowns

### ISSUE THREAD

**Issue by wikosoft-GmbH** [mikerodham/vue-dropdowns#14]
Hi, I have three dropdowns that are connected. You select something in the first, the second gets updated accordingly. Now, the problem that I have is that I can't update the second/third dropdown to switch back to the 'Please select' when I update the first one. Instead, the old name in the second dropdown stays the same, and when I change my first dropdown, the second dropdown's options update, but I am unable to set back the 'Please select' placeholder for the second one.  
This is because  `this.selectedOption = this.selected;` is in `mounted()` and `this.selectedOption = option;` is in the `updateOption()`
I don't know what to do, I tried changing the :selected, but that obviously didn't work.
I can't really change up the `v-on:updateOption` because of the way my dropdowns work and because If I put 2 methods or more in the updateOption, it's not gonna work.

**Comment by mikerodham** [comment]
Hey @wikosoft! 

I haven't really maintained this package much and it was something I kept writing over and over again for my old job in different projects so I put it on here purely just to save time. Perhaps in the future (hopefully near future!) I will look at overhauling this to be compatible with Vue 3 and their new composition API.

That being said, I can see a really simple way to help you solve your issue.

If you take the main [Dropdown.vue](https://raw.githubusercontent.com/mikerodham/vue-dropdowns/master/Dropdown.vue) file and it's raw contents and create it locally inside project so you can make easy modifications to it then change your imports to import it from there.

You could add something like the following:

```
export default {

 // Setup the functionality to watch the incoming props for changes
 // Choose one of the functions below to best suit your needs.

  watch: {
    selected: function (newValue) {
      // Here we are watching the selected prop, so if it changes
      // we can update it inside this component too.

     this.selectedOption = newValue;
    },
    
    // You could also watch the options array so every time the options change
    // then reset the selectedOption back to default
    options: function (newValue) {
      if(Array.isArray(newValue) && newValue.length > 0) {
        this.selectedOption = {
          name: '',
        }
      }
    }
  }
}
```

By adding this when you perform an update on a sibling component you can update this to refer back to normal.

If you need some further help, setup a codepen or similar so I can replicate on my end and modify for you. Hope this helps.

**Comment by wikosoft-GmbH** [comment]
We managed to get it working by re-defining an array of objects for every `v-on:updateOption`, so that for the first dropdown we have:

```
this.selected[1].name = payload.name;
this.selected[2].name = undefined;
this.selected[3].name = undefined;
```
then for the second we have 
```
this.selected[2].name = payload.name;
this.selected[3].name = undefined;
```
...etc. This works fine, I guess
