### ISSUE TITLE
Dropdown menu doesn't display without extra styles

### ISSUE THREAD

**Issue by aralikearachnid** [mikerodham/vue-dropdowns#4]
I found that when I click on the li with class "dropdown-toggle", the menu doesn't open unless I add the following to my styles: 

```
.dropdown-menu {
     display: block;
}
```

**Comment by mikerodham** [comment]
@sandramedina I'm looking in to this now.

**Comment by mikerodham** [comment]
@sandramedina I couldn't replicate this issue, could you provide a code sample I could try out? One thing I did notice is that this component requires a sass-loader so I've converted back to css to remove that dependency.

**Comment by aralikearachnid** [comment]
Hm, strange. I also converted from sass to css because my project doesn't have a sass-loader, so I expected you might run into the issue when you tried doing that but it sounds like it went fine for you. Instead of getting it from npm though I just added Dropdown.vue to my project and followed the usage instructions. Perhaps that's why the issue happened...? If that's possible, then feel free to close the issue because your instructions clearly suggest using npm.

**Comment by mikerodham** [comment]
It should work just doing that also, then you just need to register the component to Vue which you can do with `Vue.component('dropdown', require('path/to/component.vue');` but I assume you've already tried that?

Try with NPM and see how that goes.
